chore: take upstream changes

diff --git a/.github/workflows/__app-deploy.yml b/.github/workflows/__app-deploy.yml
--- a/.github/workflows/__app-deploy.yml
+++ b/.github/workflows/__app-deploy.yml
@@ -3,6 +3,15 @@ name: __Application Deployment
 on:
   workflow_call:
     inputs:
+      artifact-source:
+        required: true
+        type: string
+        # supported values:
+        # - workflow -> artifacts produced by the app-ci-cd workflow stored against the workflow run
+        # - release -> artifacts produced by the app-ci-cd workflow stored against a github release
+      cancel-in-progress:
+        type: boolean
+        default: false
       docker-image-tag:
         required: true
         type: string
@@ -20,13 +29,22 @@ jobs:
 
   run:
     runs-on: ubuntu-latest
-    concurrency: deploy_${{ inputs.environment-name }}
+    concurrency:
+      group: deploy_${{ inputs.environment-name }}
+      cancel-in-progress: ${{ inputs.cancel-in-progress }}
     environment: ${{ inputs.environment-name }}
 
     steps:
       - uses: actions/checkout@v4 # need to checkout (again) so that our custom action and deployment script is available
 
+      - name: Assert artifact-source
+        if: ${{ !contains(fromJSON('["workflow", "release"]'), inputs.artifact-source) }}
+        run: |
+          echo "Invalid artifact source '${{ inputs.artifact-source }}'. Supported values are 'workflow' and 'release'."
+          exit 1
+
       - name: Download release artifacts
+        if: inputs.artifact-source == 'release'
         uses: dsaltares/fetch-gh-release-asset@aa2ab1243d6e0d5b405b973c89fa4d06a2d0fff7 # <- 1.1.2
         with:
           version: 'tags/${{ inputs.git-tag }}'
@@ -35,7 +53,15 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Extract release artifacts
+        if: inputs.artifact-source == 'release'
         run: mkdir ./out && tar -xvf ./obj/release.tar.gz -C $_
+
+      - name: Download workflow artifacts
+        if: inputs.artifact-source == 'workflow'
+        uses: actions/download-artifact@v5
+        with:
+          name: release-artifacts
+          path: ./out
 
       - name: Azure login
         uses: ./.github/actions/azure-login
@@ -117,10 +143,9 @@ jobs:
             }
 
       - name: Azure Function App (internalapi) - File substitution in appsettings
-        uses: joshlrogers/variable-substitution@602057bea9ec150e2142bbae25ed9a64da175569 # <- v1.1.5
+        uses: ornskoldsvikskommun/variable-substitution@327f54c15b30bf6ee7ee5201646a79b45e863611 # <-  Feb 18, 2025 on master
         with:
           files: ./out/Template.Functions/appsettings.json
-          splitChar: '_'
 
       - name: Deploy SQL database migration
         uses: ./.github/actions/sql-action # <- replace with: MRI-Software/sql-action@v1
